#ifndef PG_GENERAL_LEDGER_DATABASE_DBSQL_IMPLEMENTATIONS_H
#define PG_GENERAL_LEDGER_DATABASE_DBSQL_IMPLEMENTATIONS_H

#include "dbsqlstatements.h"
#include "dbsql_mysql.h"

#endif      //  PG_GENERAL_LEDGER_DATABASE_DBSQL_IMPLEMENTATIONS_H

